# Generated by Django 2.1.9 on 2021-06-10 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import flite.users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210603_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, default=flite.users.utils.generate_transaction_reference, max_length=15),
        ),
    ]
